---
  - name: rediscover host
    local_action: check_mk_agent_discover_services url="{{ check_mk_agent_baseurl }}" username="{{ check_mk_agent_automation_user }}" secret="{{ check_mk_agent_automation_key }}" hostname="{{ ansible_hostname }}"
    notify: activate changes

  - name: activate changes
    local_action: check_mk_agent_activate_changes url="{{ check_mk_agent_baseurl }}" username="{{ check_mk_agent_automation_user }}" secret="{{ check_mk_agent_automation_key }}"

