---
  - name: rediscover host
    local_action: check_mk_agent_api url="{{ check_mk_agent_baseurl }}" username="{{ check_mk_agent_automation_user }}" secret="{{ check_mk_agent_automation_key }}" hostname="{{ ansible_hostname }}" action="discover_services"
    notify: activate changes

  - name: activate changes
    local_action: check_mk_agent_api url="{{ check_mk_agent_baseurl }}" username="{{ check_mk_agent_automation_user }}" secret="{{ check_mk_agent_automation_key }}" hostname="{{ ansible_hostname }}" action="activate_changes"

